//! PostTag DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PostTag;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PostTag
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePostTagDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "post_id")]
    pub post_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "tag_id")]
    pub tag_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PostTag
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePostTagDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "post_id")]
    pub post_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "tag_id")]
    pub tag_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PostTag
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPostTagDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "post_id")]
    pub post_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "tag_id")]
    pub tag_id: Option<Uuid>,
}

impl PatchPostTagDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.post_id.is_some() || self.tag_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PostTag entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PostTagResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub post_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub tag_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PostTag entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PostTagListResponseDto {
    /// List of items
    pub items: Vec<PostTagResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PostTagListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PostTagResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PostTagSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub post_id: Uuid,
    pub tag_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PostTag> for PostTagResponseDto {
    fn from(entity: PostTag) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            post_id: entity.post_id,
            tag_id: entity.tag_id,
            metadata: entity.metadata,
        }
    }
}

impl From<PostTag> for PostTagSummaryDto {
    fn from(entity: PostTag) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            post_id: entity.post_id,
            tag_id: entity.tag_id,
            created_at,
        }
    }
}

impl From<CreatePostTagDto> for PostTag {
    fn from(dto: CreatePostTagDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            post_id: dto.post_id,
            tag_id: dto.tag_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PostTag> for PostTagResponseDto {
    fn from(entity: &PostTag) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            post_id: entity.post_id.clone(),
            tag_id: entity.tag_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePostTagDto> for PostTag {
    fn from_create_dto(dto: CreatePostTagDto) -> backbone_core::ServiceResult<Self> {
        Ok(PostTag::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePostTagDto> for PostTag {
    fn apply_update(mut self, dto: UpdatePostTagDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.post_id = dto.post_id;
        self.tag_id = dto.tag_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PostTag here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
