//! Post DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Post;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Post
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePostDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "blog_id")]
    pub blog_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub slug: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub teaser: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cover: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "author_officer")]
    pub author_officer: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "author_name")]
    pub author_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_published")]
    pub is_published: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "published_date")]
    pub published_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "post_date")]
    pub post_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub visits: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_comments")]
    pub allow_comments: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "archived_at")]
    pub archived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "archived_by_blog_id")]
    pub archived_by_blog_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Post
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePostDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "blog_id")]
    pub blog_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "website_id")]
    pub website_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub slug: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub teaser: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cover: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "author_officer")]
    pub author_officer: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "author_name")]
    pub author_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_published")]
    pub is_published: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "published_date")]
    pub published_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "post_date")]
    pub post_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub visits: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_comments")]
    pub allow_comments: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "archived_at")]
    pub archived_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "archived_by_blog_id")]
    pub archived_by_blog_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Post
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPostDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "blog_id")]
    pub blog_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "website_id")]
    pub website_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub teaser: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cover: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "author_officer")]
    pub author_officer: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "author_name")]
    pub author_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_published")]
    pub is_published: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "published_date")]
    pub published_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "post_date")]
    pub post_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visits: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "allow_comments")]
    pub allow_comments: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "archived_at")]
    pub archived_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "archived_by_blog_id")]
    pub archived_by_blog_id: Option<Uuid>,
}

impl PatchPostDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.blog_id.is_some() || self.website_id.is_some() || self.title.is_some() || self.slug.is_some() || self.content.is_some() || self.teaser.is_some() || self.cover.is_some() || self.author_officer.is_some() || self.author_name.is_some() || self.is_published.is_some() || self.published_date.is_some() || self.post_date.is_some() || self.visits.is_some() || self.allow_comments.is_some() || self.archived_at.is_some() || self.archived_by_blog_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Post entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PostResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub blog_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub website_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub slug: String,
    pub content: Option<String>,
    pub teaser: Option<String>,
    pub cover: Option<serde_json::Value>,
    pub author_officer: Option<Uuid>,
    pub author_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_published: bool,
    pub published_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub post_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub visits: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub allow_comments: bool,
    pub archived_at: Option<DateTime<Utc>>,
    pub archived_by_blog_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Post entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PostListResponseDto {
    /// List of items
    pub items: Vec<PostResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PostListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PostResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PostSummaryDto {
    pub id: Uuid,
    pub blog_id: Uuid,
    pub website_id: Uuid,
    pub title: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Post> for PostResponseDto {
    fn from(entity: Post) -> Self {
        Self {
            id: entity.id,
            blog_id: entity.blog_id,
            website_id: entity.website_id,
            title: entity.title,
            slug: entity.slug,
            content: entity.content,
            teaser: entity.teaser,
            cover: entity.cover,
            author_officer: entity.author_officer,
            author_name: entity.author_name,
            is_published: entity.is_published,
            published_date: entity.published_date,
            post_date: entity.post_date,
            visits: entity.visits,
            allow_comments: entity.allow_comments,
            archived_at: entity.archived_at,
            archived_by_blog_id: entity.archived_by_blog_id,
            metadata: entity.metadata,
        }
    }
}

impl From<Post> for PostSummaryDto {
    fn from(entity: Post) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            blog_id: entity.blog_id,
            website_id: entity.website_id,
            title: entity.title,
            created_at,
        }
    }
}

impl From<CreatePostDto> for Post {
    fn from(dto: CreatePostDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            blog_id: dto.blog_id,
            website_id: dto.website_id,
            title: dto.title,
            slug: dto.slug,
            content: dto.content,
            teaser: dto.teaser,
            cover: dto.cover,
            author_officer: dto.author_officer,
            author_name: dto.author_name,
            is_published: dto.is_published,
            published_date: dto.published_date,
            post_date: dto.post_date,
            visits: dto.visits,
            allow_comments: dto.allow_comments,
            archived_at: dto.archived_at,
            archived_by_blog_id: dto.archived_by_blog_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Post> for PostResponseDto {
    fn from(entity: &Post) -> Self {
        Self {
            id: entity.id.clone(),
            blog_id: entity.blog_id.clone(),
            website_id: entity.website_id.clone(),
            title: entity.title.clone(),
            slug: entity.slug.clone(),
            content: entity.content.clone(),
            teaser: entity.teaser.clone(),
            cover: entity.cover.clone(),
            author_officer: entity.author_officer.clone(),
            author_name: entity.author_name.clone(),
            is_published: entity.is_published.clone(),
            published_date: entity.published_date.clone(),
            post_date: entity.post_date.clone(),
            visits: entity.visits.clone(),
            allow_comments: entity.allow_comments.clone(),
            archived_at: entity.archived_at.clone(),
            archived_by_blog_id: entity.archived_by_blog_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePostDto> for Post {
    fn from_create_dto(dto: CreatePostDto) -> backbone_core::ServiceResult<Self> {
        Ok(Post::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePostDto> for Post {
    fn apply_update(mut self, dto: UpdatePostDto) -> backbone_core::ServiceResult<Self> {
        self.blog_id = dto.blog_id;
        self.website_id = dto.website_id;
        self.title = dto.title;
        self.slug = dto.slug;
        self.content = dto.content;
        self.teaser = dto.teaser;
        self.cover = dto.cover;
        self.author_officer = dto.author_officer;
        self.author_name = dto.author_name;
        self.is_published = dto.is_published;
        self.published_date = dto.published_date;
        self.post_date = dto.post_date;
        self.visits = dto.visits;
        self.allow_comments = dto.allow_comments;
        self.archived_at = dto.archived_at;
        self.archived_by_blog_id = dto.archived_by_blog_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Post here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
