//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod blog_specification;
pub mod blog_audit_log_specification;
pub mod post_specification;
pub mod post_tag_specification;
pub mod post_view_receipt_specification;
pub mod tag_category_specification;
pub mod tag_specification;

// <<< CUSTOM
// END CUSTOM
