//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod blog_domain_policy;
pub mod blog_audit_log_domain_policy;
pub mod post_domain_policy;
pub mod post_tag_domain_policy;
pub mod post_view_receipt_domain_policy;
pub mod tag_category_domain_policy;
pub mod tag_domain_policy;

pub use blog_domain_policy::BlogDomainPolicy;
pub use blog_audit_log_domain_policy::BlogAuditLogDomainPolicy;
pub use post_domain_policy::PostDomainPolicy;
pub use post_tag_domain_policy::PostTagDomainPolicy;
pub use post_view_receipt_domain_policy::PostViewReceiptDomainPolicy;
pub use tag_category_domain_policy::TagCategoryDomainPolicy;
pub use tag_domain_policy::TagDomainPolicy;

// <<< CUSTOM
// END CUSTOM
