//! Application service for BlogAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `blog_audit_log_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBlogAuditLogDto, UpdateBlogAuditLogDto};
use crate::domain::entity::BlogAuditLog;
use crate::infrastructure::persistence::BlogAuditLogRepository;

/// Application service for BlogAuditLog entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `blog_audit_log_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BlogAuditLogServiceCustom {
///     inner: Arc<BlogAuditLogService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BlogAuditLogService = GenericCrudService<
    BlogAuditLog,
    CreateBlogAuditLogDto,
    UpdateBlogAuditLogDto,
    BlogAuditLogRepository,
>;

// <<< CUSTOM
// END CUSTOM
