//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod blog_audit_log_service;
pub mod blog_service;
pub mod post_service;
pub mod post_tag_service;
pub mod post_view_receipt_service;
pub mod tag_category_service;
pub mod tag_service;

// <<< CUSTOM
// The verb layer (hand-written; user-owned — see metaphor.codegen.yaml):
// the typed error surface, the Tier A view-token family, the public-tier
// scope binder, the publish-notify port, and the three verb services the
// route layer composes.
pub mod blog_error;
pub mod capability;
pub mod notifier_port;
pub mod public_query_service;
pub mod site_scope;
pub mod visit_service;
// END CUSTOM

pub use blog_audit_log_service::BlogAuditLogService;
pub use blog_service::BlogService;
pub use post_service::PostService;
pub use post_tag_service::PostTagService;
pub use post_view_receipt_service::PostViewReceiptService;
pub use tag_category_service::TagCategoryService;
pub use tag_service::TagService;
// <<< CUSTOM
pub use blog_error::{BlogError, BlogResult};
pub use notifier_port::{BlogPublishNotifier, RefusingPublishNotifier};
pub use public_query_service::{DetailAnswer, ListingAnswer, PublicQueryService};
pub use visit_service::{FixedWindows, VisitRequest, VisitResponse, VisitService, VISIT_THROTTLE};
// END CUSTOM
