//! Application service for PostViewReceipt entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `post_view_receipt_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePostViewReceiptDto, UpdatePostViewReceiptDto};
use crate::domain::entity::PostViewReceipt;
use crate::infrastructure::persistence::PostViewReceiptRepository;

/// Application service for PostViewReceipt entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `post_view_receipt_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PostViewReceiptServiceCustom {
///     inner: Arc<PostViewReceiptService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PostViewReceiptService = GenericCrudService<
    PostViewReceipt,
    CreatePostViewReceiptDto,
    UpdatePostViewReceiptDto,
    PostViewReceiptRepository,
>;

// <<< CUSTOM
// END CUSTOM
