//! Application service for PostTag entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `post_tag_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::PostTag;
use crate::infrastructure::persistence::PostTagRepository;
use crate::presentation::dto::{CreatePostTagDto, UpdatePostTagDto};

/// Application service for PostTag entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `post_tag_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PostTagServiceCustom {
///     inner: Arc<PostTagService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PostTagService =
    GenericCrudService<PostTag, CreatePostTagDto, UpdatePostTagDto, PostTagRepository>;

// <<< CUSTOM
// END CUSTOM
