-- Post Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the blog.posts table.
-- Customize this file to add your initial data.

-- INSERT INTO blog.posts (
--     id,
--     company_id,
--     blog_id,
--     website_id,
--     title,
--     slug,
--     content,
--     teaser,
--     cover,
--     author_officer,
--     author_name,
--     is_published,
--     published_date,
--     post_date,
--     visits,
--     allow_comments,
--     archived_at,
--     archived_by_blog_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO blog.posts (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

