-- PostTag Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the blog.post_tags table.
-- Customize this file to add your initial data.

-- INSERT INTO blog.post_tags (
--     id,
--     company_id,
--     post_id,
--     tag_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO blog.post_tags (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

