-- PostViewReceipt Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the blog.post_view_receipts table.
-- Customize this file to add your initial data.

-- INSERT INTO blog.post_view_receipts (
--     id,
--     company_id,
--     post_id,
--     view_token,
--     window_start,
--     occurred_at
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO blog.post_view_receipts (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

