-- Audit Triggers Migration for blog module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Blog (blog.blogs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION blog.blogs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS blogs_insert_audit ON blog.blogs;
CREATE TRIGGER blogs_insert_audit BEFORE INSERT ON blog.blogs
    FOR EACH ROW EXECUTE FUNCTION blog.blogs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS blogs_update_audit ON blog.blogs;
CREATE TRIGGER blogs_update_audit BEFORE UPDATE ON blog.blogs
    FOR EACH ROW EXECUTE FUNCTION blog.blogs_audit_timestamp();

-- ==============================================================================
-- Table: Post (blog.posts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION blog.posts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS posts_insert_audit ON blog.posts;
CREATE TRIGGER posts_insert_audit BEFORE INSERT ON blog.posts
    FOR EACH ROW EXECUTE FUNCTION blog.posts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS posts_update_audit ON blog.posts;
CREATE TRIGGER posts_update_audit BEFORE UPDATE ON blog.posts
    FOR EACH ROW EXECUTE FUNCTION blog.posts_audit_timestamp();

-- ==============================================================================
-- Table: PostTag (blog.post_tags)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION blog.post_tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS post_tags_insert_audit ON blog.post_tags;
CREATE TRIGGER post_tags_insert_audit BEFORE INSERT ON blog.post_tags
    FOR EACH ROW EXECUTE FUNCTION blog.post_tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS post_tags_update_audit ON blog.post_tags;
CREATE TRIGGER post_tags_update_audit BEFORE UPDATE ON blog.post_tags
    FOR EACH ROW EXECUTE FUNCTION blog.post_tags_audit_timestamp();

-- ==============================================================================
-- Table: TagCategory (blog.tag_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION blog.tag_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tag_categories_insert_audit ON blog.tag_categories;
CREATE TRIGGER tag_categories_insert_audit BEFORE INSERT ON blog.tag_categories
    FOR EACH ROW EXECUTE FUNCTION blog.tag_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tag_categories_update_audit ON blog.tag_categories;
CREATE TRIGGER tag_categories_update_audit BEFORE UPDATE ON blog.tag_categories
    FOR EACH ROW EXECUTE FUNCTION blog.tag_categories_audit_timestamp();

-- ==============================================================================
-- Table: Tag (blog.tags)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION blog.tags_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS tags_insert_audit ON blog.tags;
CREATE TRIGGER tags_insert_audit BEFORE INSERT ON blog.tags
    FOR EACH ROW EXECUTE FUNCTION blog.tags_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS tags_update_audit ON blog.tags;
CREATE TRIGGER tags_update_audit BEFORE UPDATE ON blog.tags
    FOR EACH ROW EXECUTE FUNCTION blog.tags_audit_timestamp();

