-- Migration: Create posts table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS blog;

CREATE TABLE IF NOT EXISTS blog.posts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    blog_id UUID NOT NULL,
    website_id UUID NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content TEXT,
    teaser TEXT,
    cover JSONB,
    author_officer UUID,
    author_name TEXT,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    published_date TIMESTAMPTZ,
    post_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    visits INTEGER NOT NULL DEFAULT 0 CHECK (visits >= 0),
    allow_comments BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMPTZ,
    archived_by_blog_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_posts_blog_id_post_date ON blog.posts (blog_id, post_date);

CREATE INDEX IF NOT EXISTS idx_posts_website_id_post_date ON blog.posts (website_id, post_date);

CREATE INDEX IF NOT EXISTS idx_posts_visits ON blog.posts (visits);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_posts_metadata_gin ON blog.posts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_posts_metadata_deleted_at ON blog.posts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_posts_metadata_created_at ON blog.posts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_posts_metadata_updated_at ON blog.posts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION blog.posts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS posts_insert_audit ON blog.posts;
CREATE TRIGGER posts_insert_audit BEFORE INSERT ON blog.posts
    FOR EACH ROW EXECUTE FUNCTION blog.posts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS posts_update_audit ON blog.posts;
CREATE TRIGGER posts_update_audit BEFORE UPDATE ON blog.posts
    FOR EACH ROW EXECUTE FUNCTION blog.posts_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE blog.posts ADD CONSTRAINT fk_posts_blog_id FOREIGN KEY (blog_id) REFERENCES blog.blogs (id);
