-- Migration: Create blog_audit_log table
-- Generated by metaphor-schema

-- Create blog_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'blog_audit_event') THEN
        CREATE TYPE blog_audit_event AS ENUM ('blog_created', 'blog_updated', 'blog_archived', 'blog_unarchived', 'blog_delete_refused', 'post_created', 'post_updated', 'publish_refused', 'post_published', 'notify_parked', 'post_unpublished', 'post_archived', 'post_unarchived', 'tag_created', 'tag_updated', 'tag_deleted', 'visit_throttled', 'capability_refused');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS blog;

CREATE TABLE IF NOT EXISTS blog.blog_audit_log (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    event blog_audit_event NOT NULL,
    actor UUID,
    subject_type TEXT,
    subject_id UUID,
    detail JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_blog_audit_log_event_occurred_at ON blog.blog_audit_log (event, occurred_at);
