-- Enum types for blog module
-- Generated by metaphor-schema

-- Create blog_audit_event enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'blog_audit_event') THEN
        CREATE TYPE blog_audit_event AS ENUM ('blog_created', 'blog_updated', 'blog_archived', 'blog_unarchived', 'blog_delete_refused', 'post_created', 'post_updated', 'publish_refused', 'post_published', 'notify_parked', 'post_unpublished', 'post_archived', 'post_unarchived', 'tag_created', 'tag_updated', 'tag_deleted', 'visit_throttled', 'capability_refused');
    END IF;
END
$$;

