-- Company RLS fence for blog module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for blog.blogs
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.blogs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS blogs_company_isolation ON blog.blogs;
CREATE POLICY blogs_company_isolation ON blog.blogs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for blog.blog_audit_log
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.blog_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.blog_audit_log FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS blog_audit_log_company_isolation ON blog.blog_audit_log;
CREATE POLICY blog_audit_log_company_isolation ON blog.blog_audit_log
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for blog.posts
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.posts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS posts_company_isolation ON blog.posts;
CREATE POLICY posts_company_isolation ON blog.posts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for blog.post_tags
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.post_tags FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS post_tags_company_isolation ON blog.post_tags;
CREATE POLICY post_tags_company_isolation ON blog.post_tags
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for blog.post_view_receipts
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.post_view_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.post_view_receipts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS post_view_receipts_company_isolation ON blog.post_view_receipts;
CREATE POLICY post_view_receipts_company_isolation ON blog.post_view_receipts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for blog.tag_categories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.tag_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.tag_categories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tag_categories_company_isolation ON blog.tag_categories;
CREATE POLICY tag_categories_company_isolation ON blog.tag_categories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for blog.tags
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE blog.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog.tags FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tags_company_isolation ON blog.tags;
CREATE POLICY tags_company_isolation ON blog.tags
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

