-- Migration: Create blogs table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS blog;

CREATE TABLE IF NOT EXISTS blog.blogs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    website_id UUID NOT NULL,
    name TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    archived_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_blogs_website_id ON blog.blogs (website_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_blogs_metadata_gin ON blog.blogs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_blogs_metadata_deleted_at ON blog.blogs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_blogs_metadata_created_at ON blog.blogs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_blogs_metadata_updated_at ON blog.blogs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION blog.blogs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS blogs_insert_audit ON blog.blogs;
CREATE TRIGGER blogs_insert_audit BEFORE INSERT ON blog.blogs
    FOR EACH ROW EXECUTE FUNCTION blog.blogs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS blogs_update_audit ON blog.blogs;
CREATE TRIGGER blogs_update_audit BEFORE UPDATE ON blog.blogs
    FOR EACH ROW EXECUTE FUNCTION blog.blogs_audit_timestamp();
