//! Event handler trait for Blog events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::BlogEvent;
use backbone_messaging::EventHandler;

/// Event handler for Blog events.
/// Implement this trait to react to Blog lifecycle events.
pub trait BlogEventHandler: EventHandler<BlogEvent> {}
