//! Domain events for BlogAuditLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BlogAuditLog;

/// Domain events for BlogAuditLog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BlogAuditLog>)` variant.
pub type BlogAuditLogEvent = CrudEvent<BlogAuditLog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BlogAuditLog events.
pub type BlogAuditLogEventPublisher = Arc<dyn CrudEventPublisher<BlogAuditLog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBlogAuditLogEventPublisher = NoOpCrudEventPublisher<BlogAuditLog>;
