//! Domain events for Blog entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::Blog;
use backbone_messaging::CrudEvent;

/// Domain events for Blog — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Blog>)` variant.
pub type BlogEvent = CrudEvent<Blog>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Blog events.
pub type BlogEventPublisher = Arc<dyn CrudEventPublisher<Blog> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBlogEventPublisher = NoOpCrudEventPublisher<Blog>;
