//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod blog_audit_log_event_handlers;
pub mod blog_audit_log_events;
pub mod blog_event_handlers;
pub mod blog_events;
pub mod post_event_handlers;
pub mod post_events;
pub mod post_tag_event_handlers;
pub mod post_tag_events;
pub mod post_view_receipt_event_handlers;
pub mod post_view_receipt_events;
pub mod tag_category_event_handlers;
pub mod tag_category_events;
pub mod tag_event_handlers;
pub mod tag_events;

pub use blog_audit_log_event_handlers::BlogAuditLogEventHandler;
pub use blog_audit_log_events::{
    BlogAuditLogEvent, BlogAuditLogEventPublisher, NoopBlogAuditLogEventPublisher,
};
pub use blog_event_handlers::BlogEventHandler;
pub use blog_events::{BlogEvent, BlogEventPublisher, NoopBlogEventPublisher};
pub use post_event_handlers::PostEventHandler;
pub use post_events::{NoopPostEventPublisher, PostEvent, PostEventPublisher};
pub use post_tag_event_handlers::PostTagEventHandler;
pub use post_tag_events::{NoopPostTagEventPublisher, PostTagEvent, PostTagEventPublisher};
pub use post_view_receipt_event_handlers::PostViewReceiptEventHandler;
pub use post_view_receipt_events::{
    NoopPostViewReceiptEventPublisher, PostViewReceiptEvent, PostViewReceiptEventPublisher,
};
pub use tag_category_event_handlers::TagCategoryEventHandler;
pub use tag_category_events::{
    NoopTagCategoryEventPublisher, TagCategoryEvent, TagCategoryEventPublisher,
};
pub use tag_event_handlers::TagEventHandler;
pub use tag_events::{NoopTagEventPublisher, TagEvent, TagEventPublisher};

// <<< CUSTOM
// END CUSTOM
