//! Domain events for Post entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Post;

/// Domain events for Post — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Post>)` variant.
pub type PostEvent = CrudEvent<Post>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Post events.
pub type PostEventPublisher = Arc<dyn CrudEventPublisher<Post> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPostEventPublisher = NoOpCrudEventPublisher<Post>;
