//! Domain events for PostTag entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::PostTag;
use backbone_messaging::CrudEvent;

/// Domain events for PostTag — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PostTag>)` variant.
pub type PostTagEvent = CrudEvent<PostTag>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PostTag events.
pub type PostTagEventPublisher = Arc<dyn CrudEventPublisher<PostTag> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPostTagEventPublisher = NoOpCrudEventPublisher<PostTag>;
