//! Event handler trait for Post events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PostEvent;

/// Event handler for Post events.
/// Implement this trait to react to Post lifecycle events.
pub trait PostEventHandler: EventHandler<PostEvent> {}
