//! Event handler trait for PostViewReceipt events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PostViewReceiptEvent;

/// Event handler for PostViewReceipt events.
/// Implement this trait to react to PostViewReceipt lifecycle events.
pub trait PostViewReceiptEventHandler: EventHandler<PostViewReceiptEvent> {}
