//! Domain events for PostViewReceipt entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PostViewReceipt;

/// Domain events for PostViewReceipt — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PostViewReceipt>)` variant.
pub type PostViewReceiptEvent = CrudEvent<PostViewReceipt>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PostViewReceipt events.
pub type PostViewReceiptEventPublisher = Arc<dyn CrudEventPublisher<PostViewReceipt> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPostViewReceiptEventPublisher = NoOpCrudEventPublisher<PostViewReceipt>;
