//! Event handler trait for PostTag events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PostTagEvent;

/// Event handler for PostTag events.
/// Implement this trait to react to PostTag lifecycle events.
pub trait PostTagEventHandler: EventHandler<PostTagEvent> {}
