//! Database seeders for the blog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod blog_audit_log_seeder;
mod blog_seeder;
mod post_seeder;
mod post_tag_seeder;
mod post_view_receipt_seeder;
mod tag_category_seeder;
mod tag_seeder;

pub use blog_audit_log_seeder::SeedBlogAuditLogSeeder;
pub use blog_seeder::SeedBlogSeeder;
pub use post_seeder::SeedPostSeeder;
pub use post_tag_seeder::SeedPostTagSeeder;
pub use post_view_receipt_seeder::SeedPostViewReceiptSeeder;
pub use tag_category_seeder::SeedTagCategorySeeder;
pub use tag_seeder::SeedTagSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
