//! PostTag seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PostTag data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// POSTTAG SEEDER
// ============================================================================

/// Seeder for post_tag
pub struct SeedPostTagSeeder;

impl SeedPostTagSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPostTagSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPostTagSeeder {
    fn name(&self) -> &'static str {
        "SeedPostTagSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if blog.post_tags table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM blog.post_tags")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/post_tag_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM blog.post_tags")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
