//! Repository trait for BlogAuditLog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BlogAuditLog aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{BlogAuditEvent, BlogAuditLog};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BlogAuditLogPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BlogAuditLogPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BlogAuditLogPaginatedResult {
    pub data: Vec<BlogAuditLog>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BlogAuditLogFilter {
    pub company_id: Option<Uuid>,
    pub event: Option<BlogAuditEvent>,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
}

impl BlogAuditLogFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.event.is_some()
            || self.actor.is_some()
            || self.subject_type.is_some()
            || self.subject_id.is_some()
    }
}

/// Repository trait for BlogAuditLog aggregate
///
/// This trait defines the persistence contract for BlogAuditLog entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BlogAuditLogRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new blog_audit_log entity
    async fn save(&self, entity: &BlogAuditLog) -> Result<BlogAuditLog>;

    /// Find blog_audit_log by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BlogAuditLog>>;

    /// Find all blog_audit_log entities
    async fn find_all(&self) -> Result<Vec<BlogAuditLog>>;

    /// Update blog_audit_log by ID
    async fn update(&self, id: &str, entity: &BlogAuditLog) -> Result<Option<BlogAuditLog>>;

    /// Delete blog_audit_log by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List blog_audit_log with pagination
    async fn list(
        &self,
        params: BlogAuditLogPaginationParams,
    ) -> Result<BlogAuditLogPaginatedResult>;

    /// List blog_audit_log with pagination and filters
    async fn list_with_filters(
        &self,
        params: BlogAuditLogPaginationParams,
        filters: BlogAuditLogFilter,
    ) -> Result<BlogAuditLogPaginatedResult>;

    /// Count all blog_audit_log entities
    async fn count(&self) -> Result<u64>;

    /// Count blog_audit_log entities matching filters
    async fn count_with_filters(&self, filters: BlogAuditLogFilter) -> Result<u64>;

    /// Check if blog_audit_log exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save blog_audit_log entities
    async fn bulk_save(&self, entities: &[BlogAuditLog]) -> Result<Vec<BlogAuditLog>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
