//! Repository trait for Blog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Blog aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::Blog;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BlogPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BlogPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BlogPaginatedResult {
    pub data: Vec<Blog>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BlogFilter {
    pub company_id: Option<Uuid>,
    pub website_id: Option<Uuid>,
    pub name: Option<String>,
    pub subtitle: Option<String>,
    pub description: Option<String>,
}

impl BlogFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.website_id.is_some()
            || self.name.is_some()
            || self.subtitle.is_some()
            || self.description.is_some()
    }
}

/// Repository trait for Blog aggregate
///
/// This trait defines the persistence contract for Blog entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BlogRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new blog entity
    async fn save(&self, entity: &Blog) -> Result<Blog>;

    /// Find blog by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Blog>>;

    /// Find all blog entities
    async fn find_all(&self) -> Result<Vec<Blog>>;

    /// Update blog by ID
    async fn update(&self, id: &str, entity: &Blog) -> Result<Option<Blog>>;

    /// Delete blog by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List blog with pagination
    async fn list(&self, params: BlogPaginationParams) -> Result<BlogPaginatedResult>;

    /// List blog with pagination and filters
    async fn list_with_filters(
        &self,
        params: BlogPaginationParams,
        filters: BlogFilter,
    ) -> Result<BlogPaginatedResult>;

    /// Count all blog entities
    async fn count(&self) -> Result<u64>;

    /// Count blog entities matching filters
    async fn count_with_filters(&self, filters: BlogFilter) -> Result<u64>;

    /// Check if blog exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete blog by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted blog by ID
    async fn restore(&self, id: &str) -> Result<Option<Blog>>;

    /// List soft-deleted blog entities
    async fn list_deleted(&self, params: BlogPaginationParams) -> Result<BlogPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save blog entities
    async fn bulk_save(&self, entities: &[Blog]) -> Result<Vec<Blog>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
