//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod blog_audit_log_repository;
pub mod blog_repository;
pub mod post_repository;
pub mod post_tag_repository;
pub mod post_view_receipt_repository;
pub mod tag_category_repository;
pub mod tag_repository;

// Re-exports
pub use blog_audit_log_repository::{
    BlogAuditLogFilter, BlogAuditLogPaginatedResult, BlogAuditLogPaginationParams,
    BlogAuditLogRepository,
};
pub use blog_repository::{BlogFilter, BlogPaginatedResult, BlogPaginationParams, BlogRepository};
pub use post_repository::{PostFilter, PostPaginatedResult, PostPaginationParams, PostRepository};
pub use post_tag_repository::{
    PostTagFilter, PostTagPaginatedResult, PostTagPaginationParams, PostTagRepository,
};
pub use post_view_receipt_repository::{
    PostViewReceiptFilter, PostViewReceiptPaginatedResult, PostViewReceiptPaginationParams,
    PostViewReceiptRepository,
};
pub use tag_category_repository::{
    TagCategoryFilter, TagCategoryPaginatedResult, TagCategoryPaginationParams,
    TagCategoryRepository,
};
pub use tag_repository::{TagFilter, TagPaginatedResult, TagPaginationParams, TagRepository};
