//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod blog_repository;
pub mod blog_audit_log_repository;
pub mod post_repository;
pub mod post_tag_repository;
pub mod post_view_receipt_repository;
pub mod tag_category_repository;
pub mod tag_repository;

// Re-exports
pub use blog_repository::{
    BlogRepository,
    BlogPaginationParams,
    BlogPaginatedResult,
    BlogFilter,
};
pub use blog_audit_log_repository::{
    BlogAuditLogRepository,
    BlogAuditLogPaginationParams,
    BlogAuditLogPaginatedResult,
    BlogAuditLogFilter,
};
pub use post_repository::{
    PostRepository,
    PostPaginationParams,
    PostPaginatedResult,
    PostFilter,
};
pub use post_tag_repository::{
    PostTagRepository,
    PostTagPaginationParams,
    PostTagPaginatedResult,
    PostTagFilter,
};
pub use post_view_receipt_repository::{
    PostViewReceiptRepository,
    PostViewReceiptPaginationParams,
    PostViewReceiptPaginatedResult,
    PostViewReceiptFilter,
};
pub use tag_category_repository::{
    TagCategoryRepository,
    TagCategoryPaginationParams,
    TagCategoryPaginatedResult,
    TagCategoryFilter,
};
pub use tag_repository::{
    TagRepository,
    TagPaginationParams,
    TagPaginatedResult,
    TagFilter,
};
