//! Repository trait for PostTag aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PostTag aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PostTag;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PostTagPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PostTagPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PostTagPaginatedResult {
    pub data: Vec<PostTag>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PostTagFilter {
    pub post_id: Option<Uuid>,
    pub tag_id: Option<Uuid>,
}

impl PostTagFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.post_id.is_some() || self.tag_id.is_some()
    }
}

/// Repository trait for PostTag aggregate
///
/// This trait defines the persistence contract for PostTag entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PostTagRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new post_tag entity
    async fn save(&self, entity: &PostTag) -> Result<PostTag>;

    /// Find post_tag by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PostTag>>;

    /// Find all post_tag entities
    async fn find_all(&self) -> Result<Vec<PostTag>>;

    /// Update post_tag by ID
    async fn update(&self, id: &str, entity: &PostTag) -> Result<Option<PostTag>>;

    /// Delete post_tag by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List post_tag with pagination
    async fn list(&self, params: PostTagPaginationParams) -> Result<PostTagPaginatedResult>;

    /// List post_tag with pagination and filters
    async fn list_with_filters(&self, params: PostTagPaginationParams, filters: PostTagFilter) -> Result<PostTagPaginatedResult>;

    /// Count all post_tag entities
    async fn count(&self) -> Result<u64>;

    /// Count post_tag entities matching filters
    async fn count_with_filters(&self, filters: PostTagFilter) -> Result<u64>;

    /// Check if post_tag exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete post_tag by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted post_tag by ID
    async fn restore(&self, id: &str) -> Result<Option<PostTag>>;

    /// List soft-deleted post_tag entities
    async fn list_deleted(&self, params: PostTagPaginationParams) -> Result<PostTagPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save post_tag entities
    async fn bulk_save(&self, entities: &[PostTag]) -> Result<Vec<PostTag>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
