//! Repository trait for PostViewReceipt aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PostViewReceipt aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PostViewReceipt;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PostViewReceiptPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PostViewReceiptPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PostViewReceiptPaginatedResult {
    pub data: Vec<PostViewReceipt>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PostViewReceiptFilter {
    pub post_id: Option<Uuid>,
    pub view_token: Option<String>,
}

impl PostViewReceiptFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.post_id.is_some() || self.view_token.is_some()
    }
}

/// Repository trait for PostViewReceipt aggregate
///
/// This trait defines the persistence contract for PostViewReceipt entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PostViewReceiptRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new post_view_receipt entity
    async fn save(&self, entity: &PostViewReceipt) -> Result<PostViewReceipt>;

    /// Find post_view_receipt by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PostViewReceipt>>;

    /// Find all post_view_receipt entities
    async fn find_all(&self) -> Result<Vec<PostViewReceipt>>;

    /// Update post_view_receipt by ID
    async fn update(&self, id: &str, entity: &PostViewReceipt) -> Result<Option<PostViewReceipt>>;

    /// Delete post_view_receipt by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List post_view_receipt with pagination
    async fn list(&self, params: PostViewReceiptPaginationParams) -> Result<PostViewReceiptPaginatedResult>;

    /// List post_view_receipt with pagination and filters
    async fn list_with_filters(&self, params: PostViewReceiptPaginationParams, filters: PostViewReceiptFilter) -> Result<PostViewReceiptPaginatedResult>;

    /// Count all post_view_receipt entities
    async fn count(&self) -> Result<u64>;

    /// Count post_view_receipt entities matching filters
    async fn count_with_filters(&self, filters: PostViewReceiptFilter) -> Result<u64>;

    /// Check if post_view_receipt exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save post_view_receipt entities
    async fn bulk_save(&self, entities: &[PostViewReceipt]) -> Result<Vec<PostViewReceipt>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
