//! Repository trait for Post aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Post aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Post;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PostPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PostPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PostPaginatedResult {
    pub data: Vec<Post>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PostFilter {
    pub blog_id: Option<Uuid>,
    pub website_id: Option<Uuid>,
    pub title: Option<String>,
    pub slug: Option<String>,
    pub content: Option<String>,
    pub teaser: Option<String>,
    pub author_officer: Option<Uuid>,
    pub author_name: Option<String>,
    pub is_published: Option<bool>,
    pub allow_comments: Option<bool>,
    pub archived_by_blog_id: Option<Uuid>,
}

impl PostFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.blog_id.is_some() || self.website_id.is_some() || self.title.is_some() || self.slug.is_some() || self.content.is_some() || self.teaser.is_some() || self.author_officer.is_some() || self.author_name.is_some() || self.is_published.is_some() || self.allow_comments.is_some() || self.archived_by_blog_id.is_some()
    }
}

/// Repository trait for Post aggregate
///
/// This trait defines the persistence contract for Post entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PostRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new post entity
    async fn save(&self, entity: &Post) -> Result<Post>;

    /// Find post by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Post>>;

    /// Find all post entities
    async fn find_all(&self) -> Result<Vec<Post>>;

    /// Update post by ID
    async fn update(&self, id: &str, entity: &Post) -> Result<Option<Post>>;

    /// Delete post by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List post with pagination
    async fn list(&self, params: PostPaginationParams) -> Result<PostPaginatedResult>;

    /// List post with pagination and filters
    async fn list_with_filters(&self, params: PostPaginationParams, filters: PostFilter) -> Result<PostPaginatedResult>;

    /// Count all post entities
    async fn count(&self) -> Result<u64>;

    /// Count post entities matching filters
    async fn count_with_filters(&self, filters: PostFilter) -> Result<u64>;

    /// Check if post exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete post by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted post by ID
    async fn restore(&self, id: &str) -> Result<Option<Post>>;

    /// List soft-deleted post entities
    async fn list_deleted(&self, params: PostPaginationParams) -> Result<PostPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save post entities
    async fn bulk_save(&self, entities: &[Post]) -> Result<Vec<Post>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
