//! Repository for BlogAuditLog entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BlogAuditLog, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BlogAuditLog;

/// Table name for BlogAuditLog entities
pub const TABLE_NAME: &str = "blog.blog_audit_log";

/// Repository for BlogAuditLog entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BlogAuditLogRepository(
    backbone_orm::GenericCrudRepository<BlogAuditLog, backbone_orm::HardDelete>,
);

impl std::ops::Deref for BlogAuditLogRepository {
    type Target = backbone_orm::GenericCrudRepository<BlogAuditLog, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl BlogAuditLogRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BlogAuditLogRepository, BlogAuditLog, no_soft_delete);
