//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod blog_audit_log_repository;
mod blog_repository;
mod post_repository;
mod post_tag_repository;
mod post_view_receipt_repository;
mod tag_category_repository;
mod tag_repository;

// Custom persistence modules
// <<< CUSTOM
// The hand repositories (user-owned — see metaphor.codegen.yaml): the
// transactional SQL the verb services compose. Services hold no raw
// sqlx; every transactional method binds the company scope first.
pub mod blog_command_repository;
pub mod post_command_repository;
pub mod public_query_repository;
pub mod tag_command_repository;
pub mod visit_command_repository;
// END CUSTOM

// Re-exports
pub use blog_audit_log_repository::BlogAuditLogRepository;
pub use blog_repository::BlogRepository;
pub use post_repository::PostRepository;
pub use post_tag_repository::PostTagRepository;
pub use post_view_receipt_repository::PostViewReceiptRepository;
pub use tag_category_repository::TagCategoryRepository;
pub use tag_repository::TagRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, FilterCondition, FilterParams, PaginatedResult, PaginationInfo,
    PaginationParams, PostgresRepository, SortDirection, SortParams,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use blog_command_repository::{
    BlogCommandRepository, BlogRow, CreateBlogInput, PatchBlogInput,
};
pub use post_command_repository::{
    CreatePostInput, PatchPostInput, PostCommandRepository, PostRow, PublishOutcome,
};
pub use public_query_repository::{
    AdminState, CloudEntry, ListingItem, ListingOrder, ListingPage, ListingQuery, PublicBlog,
    PublicPostDetail, PublicQueryRepository, StateCounts, TagLite, PAGE_SIZE,
};
pub use tag_command_repository::{normalize_slug, TagCategoryRow, TagCommandRepository, TagRow};
pub use visit_command_repository::{VisitCommandRepository, VisitOutcome, RECEIPT_RETENTION_DAYS};
// END CUSTOM
