//! Repository for PostViewReceipt entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PostViewReceipt, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PostViewReceipt;

/// Table name for PostViewReceipt entities
pub const TABLE_NAME: &str = "blog.post_view_receipts";

/// Repository for PostViewReceipt entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PostViewReceiptRepository(
    backbone_orm::GenericCrudRepository<PostViewReceipt, backbone_orm::HardDelete>,
);

impl std::ops::Deref for PostViewReceiptRepository {
    type Target = backbone_orm::GenericCrudRepository<PostViewReceipt, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PostViewReceiptRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PostViewReceiptRepository, PostViewReceipt, no_soft_delete);
