//! Repository for Post entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Post, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Post;

/// Table name for Post entities
pub const TABLE_NAME: &str = "blog.posts";

/// Repository for Post entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PostRepository(
    backbone_orm::GenericCrudRepository<Post, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PostRepository {
    type Target = backbone_orm::GenericCrudRepository<Post, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PostRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PostRepository, Post, soft_delete);
