//! Repository for PostTag entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PostTag, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PostTag;

/// Table name for PostTag entities
pub const TABLE_NAME: &str = "blog.post_tags";

/// Repository for PostTag entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PostTagRepository(
    backbone_orm::GenericCrudRepository<PostTag, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PostTagRepository {
    type Target = backbone_orm::GenericCrudRepository<PostTag, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl PostTagRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PostTagRepository, PostTag, soft_delete);
