//! Validator for Blog entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Blog>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Blog;

/// Validator type alias for Blog entities.
pub type BlogValidator = EntityValidator<Blog>;

/// Build a validator for Blog with all schema-defined field rules.
pub fn blog_validator() -> BlogValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Blog| &e.name))
        .rule(OptionalNotBlank::new("subtitle", |e: &Blog| e.subtitle.as_deref()))
        .rule(OptionalNotBlank::new("description", |e: &Blog| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
