//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod blog_validator;
pub mod blog_audit_log_validator;
pub mod post_validator;
pub mod post_tag_validator;
pub mod post_view_receipt_validator;
pub mod tag_category_validator;
pub mod tag_validator;

pub use blog_validator::{BlogValidator, blog_validator};
pub use blog_audit_log_validator::{BlogAuditLogValidator, blog_audit_log_validator};
pub use post_validator::{PostValidator, post_validator};
pub use post_tag_validator::{PostTagValidator, post_tag_validator};
pub use post_view_receipt_validator::{PostViewReceiptValidator, post_view_receipt_validator};
pub use tag_category_validator::{TagCategoryValidator, tag_category_validator};
pub use tag_validator::{TagValidator, tag_validator};

// <<< CUSTOM
// END CUSTOM
