//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{EntityValidator, ValidationError, ValidationErrors, ValidationResult};

pub mod blog_audit_log_validator;
pub mod blog_validator;
pub mod post_tag_validator;
pub mod post_validator;
pub mod post_view_receipt_validator;
pub mod tag_category_validator;
pub mod tag_validator;

pub use blog_audit_log_validator::{blog_audit_log_validator, BlogAuditLogValidator};
pub use blog_validator::{blog_validator, BlogValidator};
pub use post_tag_validator::{post_tag_validator, PostTagValidator};
pub use post_validator::{post_validator, PostValidator};
pub use post_view_receipt_validator::{post_view_receipt_validator, PostViewReceiptValidator};
pub use tag_category_validator::{tag_category_validator, TagCategoryValidator};
pub use tag_validator::{tag_validator, TagValidator};

// <<< CUSTOM
// END CUSTOM
