//! Validator for PostTag entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PostTag>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::PostTag;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for PostTag entities.
pub type PostTagValidator = EntityValidator<PostTag>;

/// Build a validator for PostTag with all schema-defined field rules.
pub fn post_tag_validator() -> PostTagValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
    // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
