//! Validator for Tag entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Tag>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::Tag;
use backbone_core::RequiredString;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for Tag entities.
pub type TagValidator = EntityValidator<Tag>;

/// Build a validator for Tag with all schema-defined field rules.
pub fn tag_validator() -> TagValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Tag| &e.name))
        .rule(RequiredString::new("slug", |e: &Tag| &e.slug))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
