//! Blog Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::BlogService;
use crate::application::service::BlogAuditLogService;
use crate::application::service::PostService;
use crate::application::service::PostTagService;
use crate::application::service::PostViewReceiptService;
use crate::application::service::TagCategoryService;
use crate::application::service::TagService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Blog service
    pub blog_service: Arc<BlogService>,
    /// BlogAuditLog service
    pub blog_audit_log_service: Arc<BlogAuditLogService>,
    /// Post service
    pub post_service: Arc<PostService>,
    /// PostTag service
    pub post_tag_service: Arc<PostTagService>,
    /// PostViewReceipt service
    pub post_view_receipt_service: Arc<PostViewReceiptService>,
    /// TagCategory service
    pub tag_category_service: Arc<TagCategoryService>,
    /// Tag service
    pub tag_service: Arc<TagService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        blog_service: Arc<BlogService>,
        blog_audit_log_service: Arc<BlogAuditLogService>,
        post_service: Arc<PostService>,
        post_tag_service: Arc<PostTagService>,
        post_view_receipt_service: Arc<PostViewReceiptService>,
        tag_category_service: Arc<TagCategoryService>,
        tag_service: Arc<TagService>
    ) -> Self {
        Self {
            blog_service,
            blog_audit_log_service,
            post_service,
            post_tag_service,
            post_view_receipt_service,
            tag_category_service,
            tag_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::BlogModule) -> Self {
        Self {
            blog_service: module.blog_service.clone(),
            blog_audit_log_service: module.blog_audit_log_service.clone(),
            post_service: module.post_service.clone(),
            post_tag_service: module.post_tag_service.clone(),
            post_view_receipt_service: module.post_view_receipt_service.clone(),
            tag_category_service: module.tag_category_service.clone(),
            tag_service: module.tag_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    blog_service: Option<Arc<BlogService>>,
    blog_audit_log_service: Option<Arc<BlogAuditLogService>>,
    post_service: Option<Arc<PostService>>,
    post_tag_service: Option<Arc<PostTagService>>,
    post_view_receipt_service: Option<Arc<PostViewReceiptService>>,
    tag_category_service: Option<Arc<TagCategoryService>>,
    tag_service: Option<Arc<TagService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Blog service.
    pub fn with_blog_service(mut self, service: Arc<BlogService>) -> Self {
        self.blog_service = Some(service);
        self
    }

    /// Set the BlogAuditLog service.
    pub fn with_blog_audit_log_service(mut self, service: Arc<BlogAuditLogService>) -> Self {
        self.blog_audit_log_service = Some(service);
        self
    }

    /// Set the Post service.
    pub fn with_post_service(mut self, service: Arc<PostService>) -> Self {
        self.post_service = Some(service);
        self
    }

    /// Set the PostTag service.
    pub fn with_post_tag_service(mut self, service: Arc<PostTagService>) -> Self {
        self.post_tag_service = Some(service);
        self
    }

    /// Set the PostViewReceipt service.
    pub fn with_post_view_receipt_service(mut self, service: Arc<PostViewReceiptService>) -> Self {
        self.post_view_receipt_service = Some(service);
        self
    }

    /// Set the TagCategory service.
    pub fn with_tag_category_service(mut self, service: Arc<TagCategoryService>) -> Self {
        self.tag_category_service = Some(service);
        self
    }

    /// Set the Tag service.
    pub fn with_tag_service(mut self, service: Arc<TagService>) -> Self {
        self.tag_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            blog_service: self.blog_service.expect("blog_service is required"),
            blog_audit_log_service: self.blog_audit_log_service.expect("blog_audit_log_service is required"),
            post_service: self.post_service.expect("post_service is required"),
            post_tag_service: self.post_tag_service.expect("post_tag_service is required"),
            post_view_receipt_service: self.post_view_receipt_service.expect("post_view_receipt_service is required"),
            tag_category_service: self.tag_category_service.expect("tag_category_service is required"),
            tag_service: self.tag_service.expect("tag_service is required"),
        }
    }
}
