//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    blog_handler::create_blog_read_routes,
    blog_audit_log_handler::create_blog_audit_log_read_routes,
    post_handler::create_post_read_routes,
    post_tag_handler::create_post_tag_routes,
    post_view_receipt_handler::create_post_view_receipt_read_routes,
    tag_category_handler::create_tag_category_routes,
    tag_handler::create_tag_routes,
};

use crate::application::service::{
    BlogService,
    BlogAuditLogService,
    PostService,
    PostTagService,
    PostViewReceiptService,
    TagCategoryService,
    TagService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub blog: Arc<BlogService>,
    pub blog_audit_log: Arc<BlogAuditLogService>,
    pub post: Arc<PostService>,
    pub post_tag: Arc<PostTagService>,
    pub post_view_receipt: Arc<PostViewReceiptService>,
    pub tag_category: Arc<TagCategoryService>,
    pub tag: Arc<TagService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Blog routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_blog_read_routes(services.blog))
        // BlogAuditLog routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_blog_audit_log_read_routes(services.blog_audit_log))
        // Post routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_post_read_routes(services.post))
        // PostTag routes (12 Backbone endpoints)
        .merge(create_post_tag_routes(services.post_tag))
        // PostViewReceipt routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_post_view_receipt_read_routes(services.post_view_receipt))
        // TagCategory routes (12 Backbone endpoints)
        .merge(create_tag_category_routes(services.tag_category))
        // Tag routes (12 Backbone endpoints)
        .merge(create_tag_routes(services.tag))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn blog_routes(service: Arc<BlogService>) -> Router {
        create_blog_routes(service)
    }

    pub fn blog_audit_log_routes(service: Arc<BlogAuditLogService>) -> Router {
        create_blog_audit_log_routes(service)
    }

    pub fn post_routes(service: Arc<PostService>) -> Router {
        create_post_routes(service)
    }

    pub fn post_tag_routes(service: Arc<PostTagService>) -> Router {
        create_post_tag_routes(service)
    }

    pub fn post_view_receipt_routes(service: Arc<PostViewReceiptService>) -> Router {
        create_post_view_receipt_routes(service)
    }

    pub fn tag_category_routes(service: Arc<TagCategoryService>) -> Router {
        create_tag_category_routes(service)
    }

    pub fn tag_routes(service: Arc<TagService>) -> Router {
        create_tag_routes(service)
    }

}
