//! Public events for Blog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::types::*;

// ============================================================================
// BLOG EVENTS
// ============================================================================

/// Event published when a Blog is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogCreatedEvent {
    pub id: BlogId,
    pub data: BlogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Blog is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogUpdatedEvent {
    pub id: BlogId,
    pub data: BlogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Blog is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogDeletedEvent {
    pub id: BlogId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// BLOGAUDITLOG EVENTS
// ============================================================================

/// Event published when a BlogAuditLog is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogAuditLogCreatedEvent {
    pub id: BlogAuditLogId,
    pub data: BlogAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BlogAuditLog is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogAuditLogUpdatedEvent {
    pub id: BlogAuditLogId,
    pub data: BlogAuditLogDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BlogAuditLog is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogAuditLogDeletedEvent {
    pub id: BlogAuditLogId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// POST EVENTS
// ============================================================================

/// Event published when a Post is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostCreatedEvent {
    pub id: PostId,
    pub data: PostDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Post is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostUpdatedEvent {
    pub id: PostId,
    pub data: PostDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Post is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostDeletedEvent {
    pub id: PostId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// POSTTAG EVENTS
// ============================================================================

/// Event published when a PostTag is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTagCreatedEvent {
    pub id: PostTagId,
    pub data: PostTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PostTag is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTagUpdatedEvent {
    pub id: PostTagId,
    pub data: PostTagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PostTag is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTagDeletedEvent {
    pub id: PostTagId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// POSTVIEWRECEIPT EVENTS
// ============================================================================

/// Event published when a PostViewReceipt is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostViewReceiptCreatedEvent {
    pub id: PostViewReceiptId,
    pub data: PostViewReceiptDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PostViewReceipt is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostViewReceiptUpdatedEvent {
    pub id: PostViewReceiptId,
    pub data: PostViewReceiptDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PostViewReceipt is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostViewReceiptDeletedEvent {
    pub id: PostViewReceiptId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TAGCATEGORY EVENTS
// ============================================================================

/// Event published when a TagCategory is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryCreatedEvent {
    pub id: TagCategoryId,
    pub data: TagCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TagCategory is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryUpdatedEvent {
    pub id: TagCategoryId,
    pub data: TagCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TagCategory is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryDeletedEvent {
    pub id: TagCategoryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TAG EVENTS
// ============================================================================

/// Event published when a Tag is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCreatedEvent {
    pub id: TagId,
    pub data: TagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Tag is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagUpdatedEvent {
    pub id: TagId,
    pub data: TagDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Tag is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagDeletedEvent {
    pub id: TagId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Blog module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BlogEvent {
    BlogCreated(BlogCreatedEvent),
    BlogUpdated(BlogUpdatedEvent),
    BlogDeleted(BlogDeletedEvent),
    BlogAuditLogCreated(BlogAuditLogCreatedEvent),
    BlogAuditLogUpdated(BlogAuditLogUpdatedEvent),
    BlogAuditLogDeleted(BlogAuditLogDeletedEvent),
    PostCreated(PostCreatedEvent),
    PostUpdated(PostUpdatedEvent),
    PostDeleted(PostDeletedEvent),
    PostTagCreated(PostTagCreatedEvent),
    PostTagUpdated(PostTagUpdatedEvent),
    PostTagDeleted(PostTagDeletedEvent),
    PostViewReceiptCreated(PostViewReceiptCreatedEvent),
    PostViewReceiptUpdated(PostViewReceiptUpdatedEvent),
    PostViewReceiptDeleted(PostViewReceiptDeletedEvent),
    TagCategoryCreated(TagCategoryCreatedEvent),
    TagCategoryUpdated(TagCategoryUpdatedEvent),
    TagCategoryDeleted(TagCategoryDeletedEvent),
    TagCreated(TagCreatedEvent),
    TagUpdated(TagUpdatedEvent),
    TagDeleted(TagDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for BlogEventMetadata {
    fn default() -> Self {
        Self {
            module: "blog",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
