//! Blog Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Blog exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use blog::exports::{BlogDto};
//! ```

mod events;
mod services;
mod types;

// Re-export all public types
pub use events::*;
pub use services::*;
pub use types::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `BlogDto` - Data transfer object for Blog
/// - `BlogSummary` - Summary view of Blog
/// - `BlogId` - Type-safe ID wrapper
/// - `BlogAuditLogDto` - Data transfer object for BlogAuditLog
/// - `BlogAuditLogSummary` - Summary view of BlogAuditLog
/// - `BlogAuditLogId` - Type-safe ID wrapper
/// - `PostDto` - Data transfer object for Post
/// - `PostSummary` - Summary view of Post
/// - `PostId` - Type-safe ID wrapper
/// - `PostTagDto` - Data transfer object for PostTag
/// - `PostTagSummary` - Summary view of PostTag
/// - `PostTagId` - Type-safe ID wrapper
/// - `PostViewReceiptDto` - Data transfer object for PostViewReceipt
/// - `PostViewReceiptSummary` - Summary view of PostViewReceipt
/// - `PostViewReceiptId` - Type-safe ID wrapper
/// - `TagCategoryDto` - Data transfer object for TagCategory
/// - `TagCategorySummary` - Summary view of TagCategory
/// - `TagCategoryId` - Type-safe ID wrapper
/// - `TagDto` - Data transfer object for Tag
/// - `TagSummary` - Summary view of Tag
/// - `TagId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `BlogCreatedEvent` - Published when Blog is created
/// - `BlogUpdatedEvent` - Published when Blog is updated
/// - `BlogDeletedEvent` - Published when Blog is deleted
/// - `BlogAuditLogCreatedEvent` - Published when BlogAuditLog is created
/// - `BlogAuditLogUpdatedEvent` - Published when BlogAuditLog is updated
/// - `BlogAuditLogDeletedEvent` - Published when BlogAuditLog is deleted
/// - `PostCreatedEvent` - Published when Post is created
/// - `PostUpdatedEvent` - Published when Post is updated
/// - `PostDeletedEvent` - Published when Post is deleted
/// - `PostTagCreatedEvent` - Published when PostTag is created
/// - `PostTagUpdatedEvent` - Published when PostTag is updated
/// - `PostTagDeletedEvent` - Published when PostTag is deleted
/// - `PostViewReceiptCreatedEvent` - Published when PostViewReceipt is created
/// - `PostViewReceiptUpdatedEvent` - Published when PostViewReceipt is updated
/// - `PostViewReceiptDeletedEvent` - Published when PostViewReceipt is deleted
/// - `TagCategoryCreatedEvent` - Published when TagCategory is created
/// - `TagCategoryUpdatedEvent` - Published when TagCategory is updated
/// - `TagCategoryDeletedEvent` - Published when TagCategory is deleted
/// - `TagCreatedEvent` - Published when Tag is created
/// - `TagUpdatedEvent` - Published when Tag is updated
/// - `TagDeletedEvent` - Published when Tag is deleted
pub struct ExportSummary;
