//! Public types for Blog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// BLOG TYPES
// ============================================================================

/// Type-safe ID for Blog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BlogId(pub Uuid);

impl BlogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BlogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BlogId> for Uuid {
    fn from(id: BlogId) -> Self {
        id.0
    }
}

/// Data transfer object for Blog
///
/// This is the public representation of Blog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogDto {
    pub id: BlogId,
    pub website_id: Uuid,
    pub name: String,
    pub subtitle: Option<String>,
    pub description: Option<String>,
    pub archived_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Blog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogSummary {
    pub id: BlogId,
    pub name: String,
}

/// Reference to Blog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogRef {
    pub id: BlogId,
}

// ============================================================================
// BLOGAUDITLOG TYPES
// ============================================================================

/// Type-safe ID for BlogAuditLog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BlogAuditLogId(pub Uuid);

impl BlogAuditLogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BlogAuditLogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BlogAuditLogId> for Uuid {
    fn from(id: BlogAuditLogId) -> Self {
        id.0
    }
}

/// Data transfer object for BlogAuditLog
///
/// This is the public representation of BlogAuditLog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogAuditLogDto {
    pub id: BlogAuditLogId,
    pub event: BlogAuditEvent,
    pub actor: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub detail: Option<serde_json::Value>,
    pub occurred_at: DateTime<Utc>,
}

/// Summary view of BlogAuditLog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogAuditLogSummary {
    pub id: BlogAuditLogId,
}

/// Reference to BlogAuditLog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlogAuditLogRef {
    pub id: BlogAuditLogId,
}

// ============================================================================
// POST TYPES
// ============================================================================

/// Type-safe ID for Post
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PostId(pub Uuid);

impl PostId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PostId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PostId> for Uuid {
    fn from(id: PostId) -> Self {
        id.0
    }
}

/// Data transfer object for Post
///
/// This is the public representation of Post for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostDto {
    pub id: PostId,
    pub blog_id: Uuid,
    pub website_id: Uuid,
    pub title: String,
    pub slug: String,
    pub content: Option<String>,
    pub teaser: Option<String>,
    pub cover: Option<serde_json::Value>,
    pub author_officer: Option<Uuid>,
    pub author_name: Option<String>,
    pub is_published: bool,
    pub published_date: Option<DateTime<Utc>>,
    pub post_date: DateTime<Utc>,
    pub visits: i32,
    pub allow_comments: bool,
    pub archived_at: Option<DateTime<Utc>>,
    pub archived_by_blog_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Post for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostSummary {
    pub id: PostId,
    pub title: String,
    pub author_name: Option<String>,
}

/// Reference to Post for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostRef {
    pub id: PostId,
}

// ============================================================================
// POSTTAG TYPES
// ============================================================================

/// Type-safe ID for PostTag
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PostTagId(pub Uuid);

impl PostTagId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PostTagId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PostTagId> for Uuid {
    fn from(id: PostTagId) -> Self {
        id.0
    }
}

/// Data transfer object for PostTag
///
/// This is the public representation of PostTag for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTagDto {
    pub id: PostTagId,
    pub post_id: Uuid,
    pub tag_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of PostTag for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTagSummary {
    pub id: PostTagId,
}

/// Reference to PostTag for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTagRef {
    pub id: PostTagId,
}

// ============================================================================
// POSTVIEWRECEIPT TYPES
// ============================================================================

/// Type-safe ID for PostViewReceipt
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PostViewReceiptId(pub Uuid);

impl PostViewReceiptId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PostViewReceiptId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PostViewReceiptId> for Uuid {
    fn from(id: PostViewReceiptId) -> Self {
        id.0
    }
}

/// Data transfer object for PostViewReceipt
///
/// This is the public representation of PostViewReceipt for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostViewReceiptDto {
    pub id: PostViewReceiptId,
    pub post_id: Uuid,
    pub view_token: String,
    pub window_start: DateTime<Utc>,
    pub occurred_at: DateTime<Utc>,
}

/// Summary view of PostViewReceipt for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostViewReceiptSummary {
    pub id: PostViewReceiptId,
}

/// Reference to PostViewReceipt for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostViewReceiptRef {
    pub id: PostViewReceiptId,
}

// ============================================================================
// TAGCATEGORY TYPES
// ============================================================================

/// Type-safe ID for TagCategory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TagCategoryId(pub Uuid);

impl TagCategoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TagCategoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TagCategoryId> for Uuid {
    fn from(id: TagCategoryId) -> Self {
        id.0
    }
}

/// Data transfer object for TagCategory
///
/// This is the public representation of TagCategory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryDto {
    pub id: TagCategoryId,
    pub name: String,
    pub metadata: serde_json::Value,
}

/// Summary view of TagCategory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategorySummary {
    pub id: TagCategoryId,
    pub name: String,
}

/// Reference to TagCategory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagCategoryRef {
    pub id: TagCategoryId,
}

// ============================================================================
// TAG TYPES
// ============================================================================

/// Type-safe ID for Tag
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TagId(pub Uuid);

impl TagId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TagId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TagId> for Uuid {
    fn from(id: TagId) -> Self {
        id.0
    }
}

/// Data transfer object for Tag
///
/// This is the public representation of Tag for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagDto {
    pub id: TagId,
    pub name: String,
    pub slug: String,
    pub category_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Tag for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagSummary {
    pub id: TagId,
    pub name: String,
}

/// Reference to Tag for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagRef {
    pub id: TagId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
