//! Blog Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod application;
pub mod domain;
pub mod exports;
pub mod infrastructure;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::BlogAuditLogService;
pub use application::service::BlogService;
pub use application::service::PostService;
pub use application::service::PostTagService;
pub use application::service::PostViewReceiptService;
pub use application::service::TagCategoryService;
pub use application::service::TagService;

use axum::Router;
use sqlx::PgPool;
use std::sync::Arc;

/// Blog module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let blog = BlogModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = blog.all_crud_routes();
/// ```
pub struct BlogModule {
    pub(crate) blog_service: Arc<BlogService>,
    pub(crate) blog_audit_log_service: Arc<BlogAuditLogService>,
    pub(crate) post_service: Arc<PostService>,
    pub(crate) post_tag_service: Arc<PostTagService>,
    pub(crate) post_view_receipt_service: Arc<PostViewReceiptService>,
    pub(crate) tag_category_service: Arc<TagCategoryService>,
    pub(crate) tag_service: Arc<TagService>,
    // <<< CUSTOM FIELDS
    // The verb layer (the guarded writers + the fence-composed reads)
    // the admin tree composes; the public tree composes from
    // BlogPublicState (it holds the host's website surface).
    pub blog_commands:
        std::sync::Arc<crate::application::service::blog_service::BlogCommandService>,
    pub post_commands:
        std::sync::Arc<crate::application::service::post_service::PostCommandService>,
    pub tag_commands: std::sync::Arc<crate::application::service::tag_service::TagCommandService>,
    pub public_queries: std::sync::Arc<
        crate::infrastructure::persistence::public_query_repository::PublicQueryRepository,
    >,
    pub website_surface: Option<std::sync::Arc<dyn backbone_website::exports::WebsiteSurface>>,
    // END CUSTOM
}

impl BlogModule {
    /// Create a new module builder
    pub fn builder() -> BlogModuleBuilder {
        BlogModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_blog_audit_log_read_routes, create_blog_read_routes, create_post_read_routes,
            create_post_tag_routes, create_post_view_receipt_read_routes,
            create_tag_category_routes, create_tag_routes,
        };

        Router::new()
            .merge(create_blog_read_routes(self.blog_service.clone()))
            .merge(create_blog_audit_log_read_routes(
                self.blog_audit_log_service.clone(),
            ))
            .merge(create_post_read_routes(self.post_service.clone()))
            .merge(create_post_tag_routes(self.post_tag_service.clone()))
            .merge(create_post_view_receipt_read_routes(
                self.post_view_receipt_service.clone(),
            ))
            .merge(create_tag_category_routes(
                self.tag_category_service.clone(),
            ))
            .merge(create_tag_routes(self.tag_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(
        note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface"
    )]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_blog_audit_log_read_routes, create_blog_read_routes, create_post_read_routes,
            create_post_tag_read_routes, create_post_view_receipt_read_routes,
            create_tag_category_read_routes, create_tag_read_routes,
        };

        Router::new()
            .merge(create_blog_read_routes(self.blog_service.clone()))
            .merge(create_blog_audit_log_read_routes(
                self.blog_audit_log_service.clone(),
            ))
            .merge(create_post_read_routes(self.post_service.clone()))
            .merge(create_post_tag_read_routes(self.post_tag_service.clone()))
            .merge(create_post_view_receipt_read_routes(
                self.post_view_receipt_service.clone(),
            ))
            .merge(create_tag_category_read_routes(
                self.tag_category_service.clone(),
            ))
            .merge(create_tag_read_routes(self.tag_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The officer tree (the full verb table — see
    /// `presentation/http/admin_routes.rs`). The host nests it behind
    /// its org session guard under the schema name; the module does
    /// not self-mount.
    pub fn admin_routes(&self) -> axum::Router {
        crate::presentation::http::blog_admin_routes(
            crate::presentation::http::BlogAdminState::from_parts(
                self.blog_commands.clone(),
                self.post_commands.clone(),
                self.tag_commands.clone(),
                self.public_queries.clone(),
                self.website_surface.clone(),
            ),
        )
    }
    // END CUSTOM
}

/// Builder for BlogModule
pub struct BlogModuleBuilder {
    db_pool: Option<PgPool>,
    // <<< CUSTOM - builder state
    publish_notifier:
        Option<std::sync::Arc<dyn crate::application::service::notifier_port::BlogPublishNotifier>>,
    website_surface: Option<std::sync::Arc<dyn backbone_website::exports::WebsiteSurface>>,
    // END CUSTOM
}

impl BlogModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            // <<< CUSTOM - builder defaults
            publish_notifier: None,
            website_surface: None,
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    /// The host's publish-notify adapter (backbone-mail side). Unset =
    /// the loud refusing default: the publish verb still commits, the
    /// notify parks as an audit row.
    pub fn with_publish_notifier(
        mut self,
        notifier: std::sync::Arc<
            dyn crate::application::service::notifier_port::BlogPublishNotifier,
        >,
    ) -> Self {
        self.publish_notifier = Some(notifier);
        self
    }

    /// The host's website surface for slug-redirect recording on the
    /// admin tree. Unset = slug changes park a WARN (the verb still
    /// commits; the redirect is best-effort by design).
    pub fn with_website_surface(
        mut self,
        surface: Option<std::sync::Arc<dyn backbone_website::exports::WebsiteSurface>>,
    ) -> Self {
        self.website_surface = surface;
        self
    }
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<BlogModule> {
        let db_pool = self
            .db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Blog service
        let blog_repository = Arc::new(BlogRepository::new(db_pool.clone()));
        let blog_service = Arc::new(BlogService::with_repository(blog_repository.clone()));

        // BlogAuditLog service
        let blog_audit_log_repository = Arc::new(BlogAuditLogRepository::new(db_pool.clone()));
        let blog_audit_log_service = Arc::new(BlogAuditLogService::with_repository(
            blog_audit_log_repository.clone(),
        ));

        // Post service
        let post_repository = Arc::new(PostRepository::new(db_pool.clone()));
        let post_service = Arc::new(PostService::with_repository(post_repository.clone()));

        // PostTag service
        let post_tag_repository = Arc::new(PostTagRepository::new(db_pool.clone()));
        let post_tag_service =
            Arc::new(PostTagService::with_repository(post_tag_repository.clone()));

        // PostViewReceipt service
        let post_view_receipt_repository =
            Arc::new(PostViewReceiptRepository::new(db_pool.clone()));
        let post_view_receipt_service = Arc::new(PostViewReceiptService::with_repository(
            post_view_receipt_repository.clone(),
        ));

        // TagCategory service
        let tag_category_repository = Arc::new(TagCategoryRepository::new(db_pool.clone()));
        let tag_category_service = Arc::new(TagCategoryService::with_repository(
            tag_category_repository.clone(),
        ));

        // Tag service
        let tag_repository = Arc::new(TagRepository::new(db_pool.clone()));
        let tag_service = Arc::new(TagService::with_repository(tag_repository.clone()));

        // <<< CUSTOM
        // The verb layer (the publish notifier defaults to the loud
        // refusing one; the surface defaults to None = redirect
        // recording parks WARNs).
        use crate::application::service::notifier_port::RefusingPublishNotifier;
        let notifier = self
            .publish_notifier
            .clone()
            .unwrap_or_else(|| std::sync::Arc::new(RefusingPublishNotifier));
        let blog_commands = std::sync::Arc::new(
            crate::application::service::blog_service::BlogCommandService::new(
                crate::infrastructure::persistence::blog_command_repository::BlogCommandRepository::new(db_pool.clone()),
            ),
        );
        let post_commands = std::sync::Arc::new(
            crate::application::service::post_service::PostCommandService::new(
                crate::infrastructure::persistence::post_command_repository::PostCommandRepository::new(db_pool.clone()),
                notifier,
            ),
        );
        let tag_commands = std::sync::Arc::new(
            crate::application::service::tag_service::TagCommandService::new(
                crate::infrastructure::persistence::tag_command_repository::TagCommandRepository::new(db_pool.clone()),
            ),
        );
        let public_queries = std::sync::Arc::new(
            crate::infrastructure::persistence::public_query_repository::PublicQueryRepository::new(
                db_pool.clone(),
            ),
        );
        // END CUSTOM

        Ok(BlogModule {
            blog_service,
            blog_audit_log_service,
            post_service,
            post_tag_service,
            post_view_receipt_service,
            tag_category_service,
            tag_service,
            // <<< CUSTOM - verb wiring
            blog_commands,
            post_commands,
            tag_commands,
            public_queries,
            website_surface: self.website_surface.clone(),
            // END CUSTOM
        })
    }
}

impl Default for BlogModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
